# syntax=docker/dockerfile:1

##
## Build
##
FROM golang:1.16-buster

LABEL app="base-{{cookiecutter.app_name}}"
LABEL REPO="https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.app_name}}"

WORKDIR /app

ADD go.mod .
ADD go.sum .
RUN go mod download
RUN go mod download github.com/apparentlymart/go-textseg
RUN go mod download github.com/ugorji/go
RUN go mod download github.com/vmihailenco/msgpack
RUN go mod download github.com/vmihailenco/tagparser